version: '3'

services:
  postgres_db:
    image: postgres
    environment: 
      POSTGRES_PASSWORD: "PostgresIP2022"
    ports:
      - "5432:5432"
    volumes:
      - /c/dev/Inspection Tools Backend/PostgreSQL_Volume:/var/lib/postgresql/data
    networks:
      - postgres-compose-network

  pgadmin_compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "root@root.com"
      PGADMIN_DEFAULT_PASSWORD: "root"
    ports:
     - "15432:80"
    depends_on:
      - postgres_db
    networks:
      - postgres-compose-network

networks: 
  postgres-compose-network:
    driver: bridge
